Fix  define ON OFF conflict with other libraries
arduino-libraries/ArduinoModbus pull request #77
Opened 2021-11-24 05:30 UTC by jahartley

The #define ON and #define OFF in modbus.h creates a conflict with Arduino Menu 4 library. It is only used once in modbus.c and can be substituted for TRUE FALSE, also defined in modbus.h

2021-11-24 05:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/arduino-libraries/ArduinoModbus?pullRequest=77) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/arduino-libraries/ArduinoModbus?pullRequest=77) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/arduino-libraries/ArduinoModbus?pullRequest=77) it.</sub>

2021-11-24 08:16 UTC, facchinm requested changes

2021-11-24 08:16 UTC, facchinm commented on src/libmodbus/modbus.c
> +                mb_mapping->tab_bits[mapping_address] = data ? TRUE : FALSE;
The PR looks fine but I'd change this line into `mb_mapping->tab_bits[mapping_address] = data ? 1 : 0;` to keep the original semantics

2021-12-02 02:02 UTC, jahartley commented
Updated per request.

2021-12-02 08:10 UTC, merged